/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary-fixed-dim': '#c1c4e6',
        'surface-variant': '#353437',
        'on-error': '#690005',
        'outline-variant': '#46464d',
        outline: '#919098',
        'on-secondary-container': '#bab1ee',
        'on-primary-fixed': '#161a33',
        'secondary-fixed': '#e5deff',
        primary: '#c1c4e6',
        'surface-dim': '#131315',
        'on-secondary': '#30295c',
        'on-error-container': '#ffdad6',
        'primary-container': '#0a0e27',
        'on-tertiary-container': '#6e7ba3',
        tertiary: '#b9c5f2',
        'surface-tint': '#c1c4e6',
        'on-primary-fixed-variant': '#414561',
        'on-tertiary-fixed': '#0b1a3d',
        error: '#ffb4ab',
        'on-tertiary-fixed-variant': '#39456b',
        'error-container': '#93000a',
        'on-secondary-fixed-variant': '#474074',
        'on-background': '#e5e1e4',
        'tertiary-fixed': '#dbe1ff',
        'primary-fixed': '#dee0ff',
        'secondary-container': '#4a4277',
        'surface-container-high': '#2a2a2c',
        'secondary-fixed-dim': '#c9bffd',
        'surface-container-low': '#1c1b1d',
        surface: '#131315',
        'on-tertiary': '#222f53',
        'on-secondary-fixed': '#1b1246',
        'surface-bright': '#39393b',
        background: '#131315',
        'on-primary-container': '#777a99',
        'surface-container': '#201f21',
        'inverse-on-surface': '#313032',
        'tertiary-fixed-dim': '#b9c5f2',
        'inverse-surface': '#e5e1e4',
        'on-surface-variant': '#c7c5ce',
        'surface-container-highest': '#353437',
        'on-primary': '#2b2f49',
        secondary: '#c9bffd',
        'surface-container-lowest': '#0e0e10',
        'inverse-primary': '#595c79',
        'on-surface': '#e5e1e4',
        'tertiary-container': '#000d31',
        accent_gold: '#FFD700',
        accent_cyan: '#00FFFF',
        accent_green: '#00FF00',
        accent_red: '#FF0000',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        base: '8px',
        sm: '12px',
        md: '24px',
        gutter: '24px',
        margin: '32px',
        lg: '40px',
        xl: '64px',
      },
      fontFamily: {
        'code-md': ['JetBrains Mono', 'monospace'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'code-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'display-lg': [
          '48px',
          { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' },
        ],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
